version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: adaptive_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  engine:
    build: ./aiBackend   # <--- Your fai server
    container_name: adaptive_engine
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      MONGO_URL: mongodb://mongo:27017/adaptive_identity

volumes:
  mongo_data: